### ISSUE TITLE
RangeError: Invalid count value

### ISSUE THREAD

**Issue by muescha** [Hocdoc/vfile-reporter-position#2]
## Description

the reporter not expects multiline positions:

## Location

https://github.com/Hocdoc/vfile-reporter-position/blob/96a53304e73461bd82f13d0d2a4fb2feaa25c84e/src/index.ts#L109-L112

here `redLineLength` gets `-1`

## Stacktrace

```shell
RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at getErrorLine (/Users/muescha/Work/gatsby/github/gatsby/node_modules/vfile-reporter-position/dist/vfile-reporter-position.cjs.development.js:89:93)
    at reportMessage (/Users/muescha/Work/gatsby/github/gatsby/node_modules/vfile-reporter-position/dist/vfile-reporter-position.cjs.development.js:66:79)
    at /Users/muescha/Work/gatsby/github/gatsby/node_modules/vfile-reporter-position/dist/vfile-reporter-position.cjs.development.js:53:12
    at Array.map (<anonymous>)
    at reportFile (/Users/muescha/Work/gatsby/github/gatsby/node_modules/vfile-reporter-position/dist/vfile-reporter-position.cjs.development.js:52:50)
    at /Users/muescha/Work/gatsby/github/gatsby/node_modules/vfile-reporter-position/dist/vfile-reporter-position.cjs.development.js:36:12
    at Array.map (<anonymous>)
    at reporterFileResult (/Users/muescha/Work/gatsby/github/gatsby/node_modules/vfile-reporter-position/dist/vfile-reporter-position.cjs.development.js:35:6)
    at reporter (/Users/muescha/Work/gatsby/github/gatsby/node_modules/vfile-reporter-position/dist/vfile-reporter-position.cjs.development.js:30:10)
```

## Monkey Patch

just to get it running:
```javascript
redLineLength = Math.max(redLineLength,0)
```

## Example

here it match the position over many lines

```shell
$ remark docs/blog/2018-06-18-moving-from-create-react-app-to-gatsby-js/ --report vfile-reporter
docs/blog/2018-06-18-moving-from-create-react-app-to-gatsby-js/index.md
   2:1-5:16  warning  Use "Gatsby" instead of "Gatsby.js"  prohibited-strings  remark-lint
  5:92-7:56  warning  Use "Gatsby" instead of "Gatsby.js"  prohibited-strings  remark-lint
```

```markdown
---
title: Moving from create-react-app to Gatsby.js
date: 2018-06-18
author: Khaled Garbaya
canonicalLink: https://khaledgarbaya.net/articles/moving-from-create-react-app-to-gatsby-js
publishedAt: Khaled Garbaya Blog
excerpt: How to Move from create-react-app to Gatsby.js
tags: [contentful, react]
---
```

```json
{
  "plugins": [
    [
      "remark-lint-prohibited-strings",
      [
        {
          "no": "[Gg]atsby[.]?[Jj][Ss]",
          "yes": "Gatsby"
        }
      ]
    ]
  ]
}
```

**Comment by Hocdoc** [comment]
Thanks again.
This should be fixed now in v0.1.5 with commit 28a63f99498cfc65a8a46603256bd9b7394a42f9 . Can you verify it with your example please?

**Comment by muescha** [comment]
still the same:
- text.length = 91 and position is 
- startColumn = 92

it seems somehow the message data is wrong :/

**Comment by Hocdoc** [comment]
Thx. The message data surprise me. I've now integrated your monkey patch in v0.1.6, that should fix the error message.

I will install and test the Remark/Gatsby-Ecosystem in the next weeks (I needed vfile-reporter-position for another project) and will check this issue again, so I leave the issue open.

**Comment by muescha** [comment]
the error is gone with the monkey patch
